from staze.core.error.error import Error


class AppError(Error): pass
